name: test_ing_mw
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.0.0+2
  firebase_core: ^2.20.0
  cloud_firestore: ^4.12.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - "assets/cerebros.png"
    - "assets/calavera.png"
    - "assets/chulo.png"
    - "assets/salir.png"
    - "assets/file.png"
    - "assets/Cancer.png"
    - "assets/NotCancer.png"
    - "assets/carga.gif"
    - "assets/bola_verde.png"
    - "assets/bola_roja.png"