// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-eXQPfPSY4q3B8V5gFb1Folak-zRfQqI',
    appId: '1:73264046356:web:855c052721f7bbde186201',
    messagingSenderId: '73264046356',
    projectId: 'ingsoftware-42f04',
    authDomain: 'ingsoftware-42f04.firebaseapp.com',
    storageBucket: 'ingsoftware-42f04.appspot.com',
    measurementId: 'G-SECW1NYXH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE2XFX3hLV5weLyvfSc-vw0rYx9dnD1LY',
    appId: '1:73264046356:android:9f99a21022492983186201',
    messagingSenderId: '73264046356',
    projectId: 'ingsoftware-42f04',
    storageBucket: 'ingsoftware-42f04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmLSdnxXDWiKh6AuaMWMmEhiDWVh54Jp4',
    appId: '1:73264046356:ios:ef9040fe556fdd84186201',
    messagingSenderId: '73264046356',
    projectId: 'ingsoftware-42f04',
    storageBucket: 'ingsoftware-42f04.appspot.com',
    iosBundleId: 'com.example.testIngMw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmLSdnxXDWiKh6AuaMWMmEhiDWVh54Jp4',
    appId: '1:73264046356:ios:67443b42fecedc0a186201',
    messagingSenderId: '73264046356',
    projectId: 'ingsoftware-42f04',
    storageBucket: 'ingsoftware-42f04.appspot.com',
    iosBundleId: 'com.example.testIngMw.RunnerTests',
  );
}
